### ISSUE TITLE
FDR : Support des langues régionales

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/ban-bal#1]
## Contexte

Le format BAL prévoit la possibilité de renseigner des libellés en langue régionale pour tous les champs texte en vigueur, et notamment pour `voie_nom`, `commune_nom`, `commune_deleguee_nom`, `lieudit_complement_nom`.

Ces libellés s'ajoutent au libellé "principal", et sont formalisés par une duplication du-dit champ, avec un suffixe (par exemple `voie_nom_bre` pour une variante en breton d'un nom de voie).

## Composants impactés

- [x] Analyseur et validateur BAL BaseAdresseNationale/bal#49
- [x] Mes Adresses BaseAdresseNationale/mes-adresses#128
- [x] Affichage des langues régionales dans l'explorateur BaseAdresseNationale/adresse.data.gouv.fr#1234
- [x] API de dépôt https://github.com/BaseAdresseNationale/api-depot/issues/17
- [x] Adaptation du Moissonneur v1
- [x] Plateforme BAN (traitements, API et production des fichiers) https://github.com/BaseAdresseNationale/ban-plateforme/issues/17
