### ISSUE TITLE
FDR : Ajouter le Catalan aux langues régionales

### ISSUE THREAD

**Issue by tmerlier** [BaseAdresseNationale/ban-bal#12]
## Contexte
Des utilisateurs nous ont demandés d'ajouter le catalan aux langues régionales.

label : `catalan`
code ISO : `cat`
drapeau :  ![image](https://user-images.githubusercontent.com/7040549/181451597-dbed1cb2-ab85-4790-ba93-045c59d92cff.png)

----------
### Prérequis

- [x] Ajouter la langue aux données partagées https://github.com/BaseAdresseNationale/shared-data/issues/1
- [x] Mettre à jour adresse.data.gouv.fr https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1256
- [x] Mettre à jour Mes adresses https://github.com/BaseAdresseNationale/mes-adresses/issues/640
- [x] Mettre à jour mes-adresses-api
- [x] Mettre à jour Validateur-bal
