### ISSUE TITLE
Sprint 2 - ID unique : User Story Dépôt V1

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-bal#14]
La Commune a déposée une BAL en V0 avec toutes ses adresses certifiées et ses uuid intégrés à la BAN.
L'utilisateur va dépôser un fichier CSV avec des uuid (des nouveaux, des identiques à la V0 et des manquants).

![UserStoryDepotBALV1](https://user-images.githubusercontent.com/7045982/187670226-08695853-85aa-4591-9e92-1ae156465ab0.png)

* [ ] ticket : https://github.com/BaseAdresseNationale/api-depot/issues/26 à l'étape 3
* [ ] ticket : https://github.com/BaseAdresseNationale/api-depot/issues/27 à l'étape 4
* [ ] ticket : [Créer un différentiel V0 - V1 permettant de déterminer les évènements](https://github.com/BaseAdresseNationale/api-depot/issues/29)
* [ ] ticket : [Exploiter un fichier des évènements fourni via l'API](https://github.com/BaseAdresseNationale/api-depot/issues/30)
* [ ] [Prévoir le renvoi d'informations supplémentaire au besoin via l'API de dépôt](https://github.com/BaseAdresseNationale/api-depot/issues/31)
